version: "3.8"

services:
  app:
    image: ilia-mitvichin-portfolio:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - VITE_API_BASE_URL=/api
    restart: unless-stopped
