const backendErrorsMap = {
  DUBLICATE_KEY: 'DUBLICATE_KEY',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  INVALID_INPUT: 'INVALID_INPUT',
  ACTION_FORBIDDEN: 'ACTION_FORBIDDEN',
  INVALID_QUERY_PARAMETERS: 'INVALID_QUERY_PARAMETERS',
  NOT_FOUND: 'NOT_FOUND',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  CSRF_INVALID_TOKEN: 'CSRF_INVALID_TOKEN',
};

module.exports = backendErrorsMap;
