name: Deploy to Docker Hub and Render

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t mitvichin/personal-portfolio .
          docker push mitvichin/personal-portfolio

  deploy-to-render:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Trigger Render deployment
        uses: peter-evans/render-action@v1
        with:
          token: ${{ secrets.RENDER_API_KEY }}
          service_id: ${{secrets.RENDER_SERVICE_ID}}
